import { writeFile } from 'node:fs/promises';
import { loadAbiSources } from './abi-sources.mjs';

// Development-only extraction. Published builds never read sibling repositories.
const { abis, provenance } = await loadAbiSources();
const output = '// Generated by scripts/sync-abis.mjs from repository contract artifacts. Do not edit.\n'
  + 'export const CONTRACT_ABIS = ' + JSON.stringify(abis, null, 2) + ' as const;\n'
  + 'export type ContractName = keyof typeof CONTRACT_ABIS;\n'
  + 'export const ABI_SOURCE_SHA256 = ' + JSON.stringify(provenance, null, 2) + ' as const;\n';
const immutable = '\n// Readonly TypeScript declarations are not a runtime security boundary.\n'
  + 'function freezeArtifact(value: object): void {\n'
  + '  for (const child of Object.values(value)) if (child && typeof child === "object") freezeArtifact(child);\n'
  + '  Object.freeze(value);\n}\nfreezeArtifact(CONTRACT_ABIS);\nObject.freeze(ABI_SOURCE_SHA256);\n';
await writeFile(new URL('../src/abis.ts', import.meta.url), output + immutable);
console.log(`Generated ${Object.keys(abis).length} contract interfaces.`);
