/** Canonical navigator signatures derived from the repository Solidity ABI artifacts. */
export type NavigatorKind = 'OnboarderNavigator' | 'ERC20TributeNavigator' | 'NFTGatedNavigator' | 'SignalNavigator' | 'TimelockNavigator' | 'VestingNavigator' | 'BudgetNavigator' | 'SubscriptionNavigator';
export interface NavigatorDeployConfig {
  OnboarderNavigator: {
    daoShip: string;
    shareMultiplier: bigint;
    lootMultiplier: bigint;
    pricePerUnit: bigint;
    sharesPerUnit: bigint;
    lootPerUnit: bigint;
    minTribute: bigint;
    expiry: bigint;
    mintCap: bigint;
    perAddressCap: bigint;
    allowlistRoot: string;
    name: string;
    description: string;
  };
  ERC20TributeNavigator: {
    daoShip: string;
    tributeToken: string;
    pricePerShare: bigint;
    pricePerLoot: bigint;
    expiry: bigint;
    mintCap: bigint;
    perAddressCap: bigint;
    allowlistRoot: string;
    name: string;
    description: string;
  };
  NFTGatedNavigator: {
    daoShip: string;
    gateToken: string;
    sharesPerHolder: bigint;
    lootPerHolder: bigint;
    requireTribute: boolean;
    tributeAmount: bigint;
    expiry: bigint;
    mintCap: bigint;
    perAddressCap: bigint;
    allowlistRoot: string;
    name: string;
    description: string;
  };
  SignalNavigator: {
    daoShip: string;
    minSharesToCreatePoll: bigint;
    minDuration: bigint;
    maxDuration: bigint;
    maxStartDelay: bigint;
    name: string;
    description: string;
  };
  TimelockNavigator: {
    daoShip: string;
    delay: bigint;
    expiryWindow: bigint;
    name: string;
    description: string;
  };
  VestingNavigator: {
    daoShip: string;
    name: string;
    description: string;
  };
  BudgetNavigator: {
    daoShip: string;
    name: string;
    description: string;
  };
  SubscriptionNavigator: {
    daoShip: string;
    tokens: readonly string[];
    feesPerPeriod: readonly bigint[];
    periodDuration: bigint;
    graceDuration: bigint;
    startTime: bigint;
    collectorRewardBps: bigint;
    burnOnCollect: boolean;
    initialMembers: readonly string[];
    name: string;
    description: string;
  };
}
export interface NavigatorReads {
  OnboarderNavigator: {
    'allowlistRoot()': readonly [];
    'allowlistRoot': readonly [];
    'daoShip()': readonly [];
    'daoShip': readonly [];
    'deployer()': readonly [];
    'deployer': readonly [];
    'expiry()': readonly [];
    'expiry': readonly [];
    'lootMultiplier()': readonly [];
    'lootMultiplier': readonly [];
    'lootPerUnit()': readonly [];
    'lootPerUnit': readonly [];
    'minTribute()': readonly [];
    'minTribute': readonly [];
    'mintCap()': readonly [];
    'mintCap': readonly [];
    'mintedTo(address)': readonly [arg0: string];
    'mintedTo': readonly [arg0: string];
    'navigatorType()': readonly [];
    'navigatorType': readonly [];
    'paused()': readonly [];
    'paused': readonly [];
    'perAddressCap()': readonly [];
    'perAddressCap': readonly [];
    'pricePerUnit()': readonly [];
    'pricePerUnit': readonly [];
    'shareMultiplier()': readonly [];
    'shareMultiplier': readonly [];
    'sharesPerUnit()': readonly [];
    'sharesPerUnit': readonly [];
    'totalMinted()': readonly [];
    'totalMinted': readonly [];
  };
  ERC20TributeNavigator: {
    'allowlistRoot()': readonly [];
    'allowlistRoot': readonly [];
    'daoShip()': readonly [];
    'daoShip': readonly [];
    'deployer()': readonly [];
    'deployer': readonly [];
    'expiry()': readonly [];
    'expiry': readonly [];
    'mintCap()': readonly [];
    'mintCap': readonly [];
    'mintedTo(address)': readonly [arg0: string];
    'mintedTo': readonly [arg0: string];
    'navigatorType()': readonly [];
    'navigatorType': readonly [];
    'paused()': readonly [];
    'paused': readonly [];
    'perAddressCap()': readonly [];
    'perAddressCap': readonly [];
    'pricePerLoot()': readonly [];
    'pricePerLoot': readonly [];
    'pricePerShare()': readonly [];
    'pricePerShare': readonly [];
    'totalMinted()': readonly [];
    'totalMinted': readonly [];
    'tributeToken()': readonly [];
    'tributeToken': readonly [];
  };
  NFTGatedNavigator: {
    'allowlistRoot()': readonly [];
    'allowlistRoot': readonly [];
    'canOnboard(address,uint256,bytes32[])': readonly [candidate: string, tokenId: bigint, proof: readonly string[]];
    'canOnboard(address,uint256)': readonly [candidate: string, tokenId: bigint];
    'claimed(uint256)': readonly [arg0: bigint];
    'claimed': readonly [arg0: bigint];
    'daoShip()': readonly [];
    'daoShip': readonly [];
    'deployer()': readonly [];
    'deployer': readonly [];
    'expiry()': readonly [];
    'expiry': readonly [];
    'gateToken()': readonly [];
    'gateToken': readonly [];
    'isEligible(address)': readonly [candidate: string];
    'isEligible': readonly [candidate: string];
    'isEligibleToken(address,uint256)': readonly [candidate: string, tokenId: bigint];
    'isEligibleToken': readonly [candidate: string, tokenId: bigint];
    'lootPerHolder()': readonly [];
    'lootPerHolder': readonly [];
    'mintCap()': readonly [];
    'mintCap': readonly [];
    'mintedTo(address)': readonly [arg0: string];
    'mintedTo': readonly [arg0: string];
    'navigatorType()': readonly [];
    'navigatorType': readonly [];
    'paused()': readonly [];
    'paused': readonly [];
    'perAddressCap()': readonly [];
    'perAddressCap': readonly [];
    'requireTribute()': readonly [];
    'requireTribute': readonly [];
    'sharesPerHolder()': readonly [];
    'sharesPerHolder': readonly [];
    'totalMinted()': readonly [];
    'totalMinted': readonly [];
    'tributeAmount()': readonly [];
    'tributeAmount': readonly [];
  };
  SignalNavigator: {
    'MAX_OPTIONS()': readonly [];
    'MAX_OPTIONS': readonly [];
    'MAX_WINDOW()': readonly [];
    'MAX_WINDOW': readonly [];
    'MIN_OPTIONS()': readonly [];
    'MIN_OPTIONS': readonly [];
    'daoShip()': readonly [];
    'daoShip': readonly [];
    'deployer()': readonly [];
    'deployer': readonly [];
    'getOptionVotes(uint256,uint8)': readonly [pollId: bigint, option: bigint];
    'getOptionVotes': readonly [pollId: bigint, option: bigint];
    'getResults(uint256)': readonly [pollId: bigint];
    'getResults': readonly [pollId: bigint];
    'hasVoted(uint256,address)': readonly [pollId: bigint, voter: string];
    'hasVoted': readonly [pollId: bigint, voter: string];
    'maxDuration()': readonly [];
    'maxDuration': readonly [];
    'maxStartDelay()': readonly [];
    'maxStartDelay': readonly [];
    'minDuration()': readonly [];
    'minDuration': readonly [];
    'minSharesToCreatePoll()': readonly [];
    'minSharesToCreatePoll': readonly [];
    'navigatorType()': readonly [];
    'navigatorType': readonly [];
    'pollCount()': readonly [];
    'pollCount': readonly [];
    'pollStatus(uint256)': readonly [pollId: bigint];
    'pollStatus': readonly [pollId: bigint];
    'polls(uint256)': readonly [arg0: bigint];
    'polls': readonly [arg0: bigint];
  };
  TimelockNavigator: {
    'MAX_DELAY()': readonly [];
    'MAX_DELAY': readonly [];
    'MAX_EXPIRY()': readonly [];
    'MAX_EXPIRY': readonly [];
    'MIN_DELAY()': readonly [];
    'MIN_DELAY': readonly [];
    'MIN_EXPIRY()': readonly [];
    'MIN_EXPIRY': readonly [];
    'RECOMMENDED_DELAY()': readonly [];
    'RECOMMENDED_DELAY': readonly [];
    'changeCount()': readonly [];
    'changeCount': readonly [];
    'daoShip()': readonly [];
    'daoShip': readonly [];
    'delay()': readonly [];
    'delay': readonly [];
    'deployer()': readonly [];
    'deployer': readonly [];
    'expiryWindow()': readonly [];
    'expiryWindow': readonly [];
    'isExecutable(uint256)': readonly [changeId: bigint];
    'isExecutable': readonly [changeId: bigint];
    'navigatorType()': readonly [];
    'navigatorType': readonly [];
    'paused()': readonly [];
    'paused': readonly [];
    'queuedChanges(uint256)': readonly [arg0: bigint];
    'queuedChanges': readonly [arg0: bigint];
  };
  VestingNavigator: {
    'claimable(uint256)': readonly [scheduleId: bigint];
    'claimable': readonly [scheduleId: bigint];
    'daoShip()': readonly [];
    'daoShip': readonly [];
    'deployer()': readonly [];
    'deployer': readonly [];
    'getSchedules(address)': readonly [beneficiary: string];
    'getSchedules': readonly [beneficiary: string];
    'navigatorType()': readonly [];
    'navigatorType': readonly [];
    'paused()': readonly [];
    'paused': readonly [];
    'scheduleCount()': readonly [];
    'scheduleCount': readonly [];
    'schedules(uint256)': readonly [arg0: bigint];
    'schedules': readonly [arg0: bigint];
    'vested(uint256)': readonly [scheduleId: bigint];
    'vested': readonly [scheduleId: bigint];
  };
  BudgetNavigator: {
    'MAX_PERIOD()': readonly [];
    'MAX_PERIOD': readonly [];
    'MIN_PERIOD()': readonly [];
    'MIN_PERIOD': readonly [];
    'budgetCount()': readonly [];
    'budgetCount': readonly [];
    'budgets(uint256)': readonly [arg0: bigint];
    'budgets': readonly [arg0: bigint];
    'daoShip()': readonly [];
    'daoShip': readonly [];
    'deployer()': readonly [];
    'deployer': readonly [];
    'navigatorType()': readonly [];
    'navigatorType': readonly [];
    'paused()': readonly [];
    'paused': readonly [];
    'remainingThisPeriod(uint256)': readonly [budgetId: bigint];
    'remainingThisPeriod': readonly [budgetId: bigint];
    'remainingTotal(uint256)': readonly [budgetId: bigint];
    'remainingTotal': readonly [budgetId: bigint];
  };
  SubscriptionNavigator: {
    'MAX_COLLECTOR_BPS()': readonly [];
    'MAX_COLLECTOR_BPS': readonly [];
    'MAX_PERIOD()': readonly [];
    'MAX_PERIOD': readonly [];
    'MIN_PERIOD()': readonly [];
    'MIN_PERIOD': readonly [];
    'NATIVE()': readonly [];
    'NATIVE': readonly [];
    'acceptedTokenCount()': readonly [];
    'acceptedTokenCount': readonly [];
    'acceptedTokens(uint256)': readonly [arg0: bigint];
    'acceptedTokens': readonly [arg0: bigint];
    'burnOnCollect()': readonly [];
    'burnOnCollect': readonly [];
    'collectorRewardBps()': readonly [];
    'collectorRewardBps': readonly [];
    'daoShip()': readonly [];
    'daoShip': readonly [];
    'deployer()': readonly [];
    'deployer': readonly [];
    'feePerPeriod(address)': readonly [arg0: string];
    'feePerPeriod': readonly [arg0: string];
    'getAcceptedTokens()': readonly [];
    'getAcceptedTokens': readonly [];
    'graceDuration()': readonly [];
    'graceDuration': readonly [];
    'inGracePeriod(address)': readonly [member: string];
    'inGracePeriod': readonly [member: string];
    'isCurrent(address)': readonly [member: string];
    'isCurrent': readonly [member: string];
    'isDelinquent(address)': readonly [member: string];
    'isDelinquent': readonly [member: string];
    'isEnrolled(address)': readonly [member: string];
    'isEnrolled': readonly [member: string];
    'navigatorType()': readonly [];
    'navigatorType': readonly [];
    'nextDeadline(address)': readonly [member: string];
    'nextDeadline': readonly [member: string];
    'paidThrough(address)': readonly [arg0: string];
    'paidThrough': readonly [arg0: string];
    'paused()': readonly [];
    'paused': readonly [];
    'periodDuration()': readonly [];
    'periodDuration': readonly [];
    'quote(uint256,address)': readonly [periods: bigint, token: string];
    'quote': readonly [periods: bigint, token: string];
    'startTime()': readonly [];
    'startTime': readonly [];
  };
}
export interface NavigatorWrites {
  OnboarderNavigator: {
    'onboard(bytes32[])': readonly [proof: readonly string[]];
    'onboard()': readonly [];
    'pause()': readonly [];
    'pause': readonly [];
    'unpause()': readonly [];
    'unpause': readonly [];
    'withdrawStuckETH(address,uint256)': readonly [to: string, amount: bigint];
    'withdrawStuckETH': readonly [to: string, amount: bigint];
  };
  ERC20TributeNavigator: {
    'onboard(uint256,uint256,bytes32[])': readonly [sharesToMint: bigint, lootToMint: bigint, proof: readonly string[]];
    'onboard(uint256,uint256)': readonly [sharesToMint: bigint, lootToMint: bigint];
    'onboardWithPermit(uint256,uint256,bytes32[],uint256,uint8,bytes32,bytes32)': readonly [sharesToMint: bigint, lootToMint: bigint, proof: readonly string[], deadline: bigint, v: bigint, r: string, s: string];
    'onboardWithPermit': readonly [sharesToMint: bigint, lootToMint: bigint, proof: readonly string[], deadline: bigint, v: bigint, r: string, s: string];
    'pause()': readonly [];
    'pause': readonly [];
    'unpause()': readonly [];
    'unpause': readonly [];
    'withdrawStuckTokens(address,address,uint256)': readonly [token: string, to: string, amount: bigint];
    'withdrawStuckTokens': readonly [token: string, to: string, amount: bigint];
  };
  NFTGatedNavigator: {
    'onboard(uint256,bytes32[])': readonly [tokenId: bigint, proof: readonly string[]];
    'onboard(uint256)': readonly [tokenId: bigint];
    'pause()': readonly [];
    'pause': readonly [];
    'unpause()': readonly [];
    'unpause': readonly [];
  };
  SignalNavigator: {
    'cancelPoll(uint256)': readonly [pollId: bigint];
    'cancelPoll': readonly [pollId: bigint];
    'createPoll(string,uint8,uint64,uint64)': readonly [question: string, optionCount: bigint, startTime: bigint, duration: bigint];
    'createPoll': readonly [question: string, optionCount: bigint, startTime: bigint, duration: bigint];
    'vote(uint256,uint8)': readonly [pollId: bigint, option: bigint];
    'vote': readonly [pollId: bigint, option: bigint];
  };
  TimelockNavigator: {
    'cancelChange(uint256)': readonly [changeId: bigint];
    'cancelChange': readonly [changeId: bigint];
    'emergencyCancelAll()': readonly [];
    'emergencyCancelAll': readonly [];
    'executeChange(uint256,bytes)': readonly [changeId: bigint, governanceConfig: string];
    'executeChange': readonly [changeId: bigint, governanceConfig: string];
    'pause()': readonly [];
    'pause': readonly [];
    'queueChange(bytes)': readonly [governanceConfig: string];
    'queueChange': readonly [governanceConfig: string];
    'unpause()': readonly [];
    'unpause': readonly [];
  };
  VestingNavigator: {
    'claim(uint256)': readonly [scheduleId: bigint];
    'claim': readonly [scheduleId: bigint];
    'createSchedule(address,uint256,uint64,uint64,uint64,bool)': readonly [beneficiary: string, totalAmount: bigint, startTime: bigint, cliffDuration: bigint, vestingDuration: bigint, isLoot: boolean];
    'createSchedule': readonly [beneficiary: string, totalAmount: bigint, startTime: bigint, cliffDuration: bigint, vestingDuration: bigint, isLoot: boolean];
    'pause()': readonly [];
    'pause': readonly [];
    'revoke(uint256)': readonly [scheduleId: bigint];
    'revoke': readonly [scheduleId: bigint];
    'unpause()': readonly [];
    'unpause': readonly [];
  };
  BudgetNavigator: {
    'cancelBudget(uint256)': readonly [budgetId: bigint];
    'cancelBudget': readonly [budgetId: bigint];
    'createBudget(address,address,uint256,uint256,uint64,uint64,uint64)': readonly [manager: string, token: string, allowancePerPeriod: bigint, totalCeiling: bigint, periodLength: bigint, startTime: bigint, endTime: bigint];
    'createBudget': readonly [manager: string, token: string, allowancePerPeriod: bigint, totalCeiling: bigint, periodLength: bigint, startTime: bigint, endTime: bigint];
    'disburse(uint256,address,uint256)': readonly [budgetId: bigint, to: string, amount: bigint];
    'disburse': readonly [budgetId: bigint, to: string, amount: bigint];
    'disburseBatch(uint256,address[],uint256[])': readonly [budgetId: bigint, to: readonly string[], amounts: readonly bigint[]];
    'disburseBatch': readonly [budgetId: bigint, to: readonly string[], amounts: readonly bigint[]];
    'pause()': readonly [];
    'pause': readonly [];
    'unpause()': readonly [];
    'unpause': readonly [];
    'updateManager(uint256,address)': readonly [budgetId: bigint, newManager: string];
    'updateManager': readonly [budgetId: bigint, newManager: string];
  };
  SubscriptionNavigator: {
    'collectFee(address)': readonly [member: string];
    'collectFee': readonly [member: string];
    'enroll(address)': readonly [member: string];
    'enroll': readonly [member: string];
    'enrollBatch(address[])': readonly [members: readonly string[]];
    'enrollBatch': readonly [members: readonly string[]];
    'pause()': readonly [];
    'pause': readonly [];
    'payFee(uint256,address)': readonly [periods: bigint, token: string];
    'payFee': readonly [periods: bigint, token: string];
    'payFeeFor(address,uint256,address)': readonly [member: string, periods: bigint, token: string];
    'payFeeFor': readonly [member: string, periods: bigint, token: string];
    'unpause()': readonly [];
    'unpause': readonly [];
    'withdrawStuckTokens(address,address,uint256)': readonly [token: string, to: string, amount: bigint];
    'withdrawStuckTokens': readonly [token: string, to: string, amount: bigint];
  };
}
export interface NavigatorReadResults {
  OnboarderNavigator: {
    'allowlistRoot()': string;
    'allowlistRoot': string;
    'daoShip()': string;
    'daoShip': string;
    'deployer()': string;
    'deployer': string;
    'expiry()': bigint;
    'expiry': bigint;
    'lootMultiplier()': bigint;
    'lootMultiplier': bigint;
    'lootPerUnit()': bigint;
    'lootPerUnit': bigint;
    'minTribute()': bigint;
    'minTribute': bigint;
    'mintCap()': bigint;
    'mintCap': bigint;
    'mintedTo(address)': bigint;
    'mintedTo': bigint;
    'navigatorType()': string;
    'navigatorType': string;
    'paused()': boolean;
    'paused': boolean;
    'perAddressCap()': bigint;
    'perAddressCap': bigint;
    'pricePerUnit()': bigint;
    'pricePerUnit': bigint;
    'shareMultiplier()': bigint;
    'shareMultiplier': bigint;
    'sharesPerUnit()': bigint;
    'sharesPerUnit': bigint;
    'totalMinted()': bigint;
    'totalMinted': bigint;
  };
  ERC20TributeNavigator: {
    'allowlistRoot()': string;
    'allowlistRoot': string;
    'daoShip()': string;
    'daoShip': string;
    'deployer()': string;
    'deployer': string;
    'expiry()': bigint;
    'expiry': bigint;
    'mintCap()': bigint;
    'mintCap': bigint;
    'mintedTo(address)': bigint;
    'mintedTo': bigint;
    'navigatorType()': string;
    'navigatorType': string;
    'paused()': boolean;
    'paused': boolean;
    'perAddressCap()': bigint;
    'perAddressCap': bigint;
    'pricePerLoot()': bigint;
    'pricePerLoot': bigint;
    'pricePerShare()': bigint;
    'pricePerShare': bigint;
    'totalMinted()': bigint;
    'totalMinted': bigint;
    'tributeToken()': string;
    'tributeToken': string;
  };
  NFTGatedNavigator: {
    'allowlistRoot()': string;
    'allowlistRoot': string;
    'canOnboard(address,uint256,bytes32[])': boolean;
    'canOnboard(address,uint256)': boolean;
    'claimed(uint256)': boolean;
    'claimed': boolean;
    'daoShip()': string;
    'daoShip': string;
    'deployer()': string;
    'deployer': string;
    'expiry()': bigint;
    'expiry': bigint;
    'gateToken()': string;
    'gateToken': string;
    'isEligible(address)': boolean;
    'isEligible': boolean;
    'isEligibleToken(address,uint256)': boolean;
    'isEligibleToken': boolean;
    'lootPerHolder()': bigint;
    'lootPerHolder': bigint;
    'mintCap()': bigint;
    'mintCap': bigint;
    'mintedTo(address)': bigint;
    'mintedTo': bigint;
    'navigatorType()': string;
    'navigatorType': string;
    'paused()': boolean;
    'paused': boolean;
    'perAddressCap()': bigint;
    'perAddressCap': bigint;
    'requireTribute()': boolean;
    'requireTribute': boolean;
    'sharesPerHolder()': bigint;
    'sharesPerHolder': bigint;
    'totalMinted()': bigint;
    'totalMinted': bigint;
    'tributeAmount()': bigint;
    'tributeAmount': bigint;
  };
  SignalNavigator: {
    'MAX_OPTIONS()': bigint;
    'MAX_OPTIONS': bigint;
    'MAX_WINDOW()': bigint;
    'MAX_WINDOW': bigint;
    'MIN_OPTIONS()': bigint;
    'MIN_OPTIONS': bigint;
    'daoShip()': string;
    'daoShip': string;
    'deployer()': string;
    'deployer': string;
    'getOptionVotes(uint256,uint8)': bigint;
    'getOptionVotes': bigint;
    'getResults(uint256)': readonly bigint[];
    'getResults': readonly bigint[];
    'hasVoted(uint256,address)': boolean;
    'hasVoted': boolean;
    'maxDuration()': bigint;
    'maxDuration': bigint;
    'maxStartDelay()': bigint;
    'maxStartDelay': bigint;
    'minDuration()': bigint;
    'minDuration': bigint;
    'minSharesToCreatePoll()': bigint;
    'minSharesToCreatePoll': bigint;
    'navigatorType()': string;
    'navigatorType': string;
    'pollCount()': bigint;
    'pollCount': bigint;
    'pollStatus(uint256)': bigint;
    'pollStatus': bigint;
    'polls(uint256)': readonly [creator: string, question: string, optionCount: bigint, snapshotTimestamp: bigint, votingStarts: bigint, votingEnds: bigint, cancelled: boolean];
    'polls': readonly [creator: string, question: string, optionCount: bigint, snapshotTimestamp: bigint, votingStarts: bigint, votingEnds: bigint, cancelled: boolean];
  };
  TimelockNavigator: {
    'MAX_DELAY()': bigint;
    'MAX_DELAY': bigint;
    'MAX_EXPIRY()': bigint;
    'MAX_EXPIRY': bigint;
    'MIN_DELAY()': bigint;
    'MIN_DELAY': bigint;
    'MIN_EXPIRY()': bigint;
    'MIN_EXPIRY': bigint;
    'RECOMMENDED_DELAY()': bigint;
    'RECOMMENDED_DELAY': bigint;
    'changeCount()': bigint;
    'changeCount': bigint;
    'daoShip()': string;
    'daoShip': string;
    'delay()': bigint;
    'delay': bigint;
    'deployer()': string;
    'deployer': string;
    'expiryWindow()': bigint;
    'expiryWindow': bigint;
    'isExecutable(uint256)': boolean;
    'isExecutable': boolean;
    'navigatorType()': string;
    'navigatorType': string;
    'paused()': boolean;
    'paused': boolean;
    'queuedChanges(uint256)': readonly [configHash: string, queuedAt: bigint, executableAfter: bigint, expiresAt: bigint, queuedBy: string, executed: boolean, cancelled: boolean];
    'queuedChanges': readonly [configHash: string, queuedAt: bigint, executableAfter: bigint, expiresAt: bigint, queuedBy: string, executed: boolean, cancelled: boolean];
  };
  VestingNavigator: {
    'claimable(uint256)': bigint;
    'claimable': bigint;
    'daoShip()': string;
    'daoShip': string;
    'deployer()': string;
    'deployer': string;
    'getSchedules(address)': readonly bigint[];
    'getSchedules': readonly bigint[];
    'navigatorType()': string;
    'navigatorType': string;
    'paused()': boolean;
    'paused': boolean;
    'scheduleCount()': bigint;
    'scheduleCount': bigint;
    'schedules(uint256)': readonly [beneficiary: string, isLoot: boolean, revoked: boolean, totalAmount: bigint, claimed: bigint, startTime: bigint, cliffEnd: bigint, vestingEnd: bigint, revokedAt: bigint];
    'schedules': readonly [beneficiary: string, isLoot: boolean, revoked: boolean, totalAmount: bigint, claimed: bigint, startTime: bigint, cliffEnd: bigint, vestingEnd: bigint, revokedAt: bigint];
    'vested(uint256)': bigint;
    'vested': bigint;
  };
  BudgetNavigator: {
    'MAX_PERIOD()': bigint;
    'MAX_PERIOD': bigint;
    'MIN_PERIOD()': bigint;
    'MIN_PERIOD': bigint;
    'budgetCount()': bigint;
    'budgetCount': bigint;
    'budgets(uint256)': readonly [manager: string, periodLength: bigint, cancelled: boolean, token: string, currentPeriodStart: bigint, startsAt: bigint, endsAt: bigint, allowancePerPeriod: bigint, totalCeiling: bigint, totalSpent: bigint, spentThisPeriod: bigint];
    'budgets': readonly [manager: string, periodLength: bigint, cancelled: boolean, token: string, currentPeriodStart: bigint, startsAt: bigint, endsAt: bigint, allowancePerPeriod: bigint, totalCeiling: bigint, totalSpent: bigint, spentThisPeriod: bigint];
    'daoShip()': string;
    'daoShip': string;
    'deployer()': string;
    'deployer': string;
    'navigatorType()': string;
    'navigatorType': string;
    'paused()': boolean;
    'paused': boolean;
    'remainingThisPeriod(uint256)': bigint;
    'remainingThisPeriod': bigint;
    'remainingTotal(uint256)': bigint;
    'remainingTotal': bigint;
  };
  SubscriptionNavigator: {
    'MAX_COLLECTOR_BPS()': bigint;
    'MAX_COLLECTOR_BPS': bigint;
    'MAX_PERIOD()': bigint;
    'MAX_PERIOD': bigint;
    'MIN_PERIOD()': bigint;
    'MIN_PERIOD': bigint;
    'NATIVE()': string;
    'NATIVE': string;
    'acceptedTokenCount()': bigint;
    'acceptedTokenCount': bigint;
    'acceptedTokens(uint256)': string;
    'acceptedTokens': string;
    'burnOnCollect()': boolean;
    'burnOnCollect': boolean;
    'collectorRewardBps()': bigint;
    'collectorRewardBps': bigint;
    'daoShip()': string;
    'daoShip': string;
    'deployer()': string;
    'deployer': string;
    'feePerPeriod(address)': bigint;
    'feePerPeriod': bigint;
    'getAcceptedTokens()': readonly string[];
    'getAcceptedTokens': readonly string[];
    'graceDuration()': bigint;
    'graceDuration': bigint;
    'inGracePeriod(address)': boolean;
    'inGracePeriod': boolean;
    'isCurrent(address)': boolean;
    'isCurrent': boolean;
    'isDelinquent(address)': boolean;
    'isDelinquent': boolean;
    'isEnrolled(address)': boolean;
    'isEnrolled': boolean;
    'navigatorType()': string;
    'navigatorType': string;
    'nextDeadline(address)': bigint;
    'nextDeadline': bigint;
    'paidThrough(address)': bigint;
    'paidThrough': bigint;
    'paused()': boolean;
    'paused': boolean;
    'periodDuration()': bigint;
    'periodDuration': bigint;
    'quote(uint256,address)': bigint;
    'quote': bigint;
    'startTime()': bigint;
    'startTime': bigint;
  };
}
